project:
  type: website
  render:
  - "*.qmd"

website:
  title: "Regex for NICAR"
  sidebar:
    contents:
        - href: index.qmd
          text: "Overview"
        - href: regex101.qmd
          text: "Regex101 version"
        - href: vscode.qmd
          text: "VS Code version"
        - cheatsheet.qmd

format:
  html:
    theme: yeti
    css: styles.css
    toc: true
